### GET
GET http://localhost:8080/obras


### POST
POST http://localhost:8080/obras
Content-Type: application/json

{
    "nomeAutor": "julinho",
    "tituloObra": "as tranças do rei careca",
    "ano": "2015",
    "isbn": "528065720",
    "doi": "8749632-24"
}

###
POST https://api.semanticscholar.org/graph/v1/paper/batch?fields=title,isOpenAccess,openAccessPdf,authors
Content-Type: application/json

{
    "ids":["649def34f8be52c8b66281af98ae884c09aef38b", "ARXIV:2106.15928"]
}


### PUT
PUT http://localhost:8080/obras/0
Content-Type: application/json

{
    "nomeAutor": "julinho",
    "tituloObra": "as tranças do rei careca",
    "ano": "2015",
    "isbn": "528065720",
    "doi": "8749632-24",
    "citacoes": [
        {
            "id": 1
        }
    ]
}


### DELETE 
DELETE http://localhost:8080/obras
Content-Type: application/json
